version: '3.8'

services:
  tradingbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-trading-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./appsettings.json:/app/appsettings.json:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - bot-network

  redis:
    image: redis:alpine
    container_name: trading-bot-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  redis-data: